# Programming Project 2 : DS-160-01
## Jalin Roberts 
- January 19, 2023
- Version0

### Question A - Create a 2-by-2 NumPy array with elements 10,20,30,40 in it.

In [51]:
import numpy as np
x = np.array([[10,20], [30,40]])
print(x)

[[10 20]
 [30 40]]


### i. Square every element of the array.

In [62]:
np.square(x)

array([[ 100,  400],
       [ 900, 1600]])

### ii. Add 100 to every element of the array.

In [54]:
np.add(x,100)

array([[110, 120],
       [130, 140]])

### iii. Multiply every element of the array by 5.

In [55]:
x * 5

array([[ 50, 100],
       [150, 200]])

### iv. Calculate the square root of each element in the array.

In [56]:
np.sqrt(x)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

### Question B - Create a 3-by-3 array containing integers from 3 to 27 in multiples of 3.

In [80]:
import numpy as np
x =  np.arange(3, 28, 3).reshape(3,3)
print(x)


[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


### Question B - Create a second 3-by-3 array with 9 elements evenly spaced between 10 and 20.

In [90]:
import numpy as np
x1 = np.linspace(10,20,9).reshape(3,3)
print(x1)

[[10.   11.25 12.5 ]
 [13.75 15.   16.25]
 [17.5  18.75 20.  ]]


### Question B - Multiply these arrays together and display the output.

In [91]:
x * x1

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

### Question C - Read these files in and stack htem into a unified dataset.

In [93]:
import numpy as np
array1=np.load("process1.npy")
array2=np.load("process2.npy")
array3=np.load("process3.npy")
array4=np.load("process4.npy")
array5=np.load("process5.npy")
array6=np.vstack ([array1,array2,array3,array4,array5])
print(array6)

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]


### Question C - Calculate the mean of each column of data.

In [13]:
print("The mean for this array is :",np.mean(array6, axis=0))


The mean for this array is : [72.  27.8 45.6 12.  47.8]


In [14]:
(58+43+58+6+74)/5

47.8